#!/usr/bin/env python2.7

import sys
import getopt
import logging
import coloredlogs
import os
import datetime
import subprocess
import time

from colorama import init,Fore, Back, Style
init(autoreset=True)
from termcolor import colored

import config

logger = logging.getLogger(__name__)
coloredlogs.install(level='DEBUG',milliseconds=True)

start_time_template = str(datetime.datetime.now())
start_time_template_seconds = time.time()
#start_time_template_minutes = int(start_time_template[-12:-10])

def usage():
  print(config.cyan + 'Usage:')
  print(__file__ + ' [-o DIRECTORY] -h -v')
  print(config.cyan + 'This script is only template which by default has only few options, and none is mandatory\n')
  print(config.lime + '   -o' + config.blue + '   directory to which will go all LOGs and TMPs')
  print(config.blue + '        default: ' + os.environ['HOME'] + '/var')
  print(config.lime + '   -v' + config.blue + '   verbose')
  print(config.lime + '   -h' + config.blue + '   help')

try:
  opts, args = getopt.getopt(sys.argv[1:], "ho:v", ["help", "output="])
except getopt.GetoptError as err:
  # print help information and exit:
  print str(err)  # will print something like "option -a not recognized"
  usage()
  sys.exit(2)
output = None
verbose = False
script_path = os.path.realpath(__file__)
scripts_home = os.path.dirname(script_path)

for o, a in opts:
  if o in ("-v", "--verbose"):
    verbose = True
  elif o in ("-h", "--help"):
    usage()
    sys.exit()
  elif o in ("-o", "--output"):
    output = a
  else:
    assert False, "unhandled option"

if output:
  new_var = output
  new_tmp = new_var + '/' + 'tmp'
  new_log = new_var + '/' + 'log'
  if not os.path.exists(new_var):
    try:
      os.mkdir(new_var)
      os.mkdir(new_tmp)
      os.mkdir(new_log)
      if verbose == True:
        logger.debug("Successfully created the directory: " + config.blue + new_var)
        logger.debug("all LOGs and TMPs will go then to: "+ config.blue + output)
    except OSError as err:
      logger.error("Creating directory failed - possibly permission denied")
      exit(2)
  else:
    if verbose == True:
      logger.debug("Directory for tmp and logs exists: " + config.blue + new_var)
else:
  new_var = config.user_home_dir + '/var'
  new_tmp = new_var + '/' + 'tmp'
  new_log = new_var + '/' + 'log'
  if not os.path.exists(new_var):
    try:
      os.mkdir(new_var)
      os.mkdir(new_tmp)
      os.mkdir(new_log)
      if verbose == True:
        logger.debug("Successfully created the directory: " + config.blue + new_var)
        logger.debug("all LOGs and TMPs will go then to: " + config.blue + new_var)
    except OSError as err:
      logger.error("Creating directory failed - possibly permission denied")
      exit(2)
  else:
    if verbose == True:
      logger.debug("Directory for tmp and logs exists: " + config.blue + new_var)

os.environ["TMP"] = new_tmp
os.environ["VAR"] = new_var
os.environ["LOG"] = new_log
os.environ["SCRIPTS_HOME"] = scripts_home

start_time_bash_seconds = time.time()
#os.system(scripts_home + '/template.bash')
subprocess.call(scripts_home + '/report.bteq', shell=True)
end_time_bash_seconds = time.time()
bash_seconds = [end_time_bash_seconds, -start_time_bash_seconds]

if verbose == True:
  logger.debug('current timestamp is: ' + config.blue + config.current_timestamp)
  logger.debug('my default ip is: ' + config.blue + config.get_ip())
  if config.office == 1:
    logger.debug(config.blue + 'office_network is present')
  elif config.vpn == 1:
    logger.debug(config.blue + 'vpn is present')
  else:
    logger.debug(config.blue + 'not connected to the office')
end_time_template_seconds = time.time()
template_seconds = [end_time_template_seconds, -start_time_template_seconds]

time_template_seconds = sum(template_seconds)
time_bash_seconds = sum(bash_seconds)

python_seconds = [time_template_seconds, -time_bash_seconds]
time_python_seconds = sum(python_seconds)

logger.debug(config.limon + "Run time: " + config.wine + "%.4f" % time_template_seconds + config.limon +  " seconds")
logger.debug(config.limon + "BASH script run for: " + config.wine + "%.4f" % time_bash_seconds + config.limon +  " seconds")
logger.debug(config.limon + "Python script run for: " + config.wine + "%.4f" % time_python_seconds + config.limon + " seconds")
logger.debug(config.limon + "Python script runtime is shorter then BASH: " + config.wine + "%.6s" % str(time_bash_seconds/time_python_seconds) + config.limon  + "x time")
